AppView/Models/ErrorViewModel.cs
namespace AppView.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

AppView/Controllers/BmiController.cs
using Microsoft.AspNetCore.Mvc;

namespace AppView.Controllers;

public class BmiController : Controller
{
    // GET
    private readonly HttpClient _httpClient;

    public BmiController()
    {
        _httpClient = new HttpClient();
    }

    public async Task<IActionResult> Calculate(double weight, double height)
    {
        var url = $"https://localhost:7195/api/Bmi/{weight}/{height}";
        var response = await _httpClient.GetAsync(url);
        if (response.IsSuccessStatusCode)
        {
            var result = await response.Content.ReadAsStringAsync();
            ViewBag.Bmi = result;
        }

        return View();
    }
}

AppView/Controllers/NhanVienController.cs
using AppData.Model;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace AppView.Controllers;

public class NhanVienController : Controller
{
    private readonly HttpClient _client;
    private NhanVien _nhanVien;

    public NhanVienController()
    {
        _client = new HttpClient();
        _nhanVien = new NhanVien();
    }

    // GET
    public async Task<IActionResult> Show()
    {
        var url = "https://localhost:7195/api/NhanVien/get-all";
        var response = await _client.GetAsync(url);
        var result = await response.Content.ReadAsStringAsync();
        var nv = JsonConvert.DeserializeObject<IEnumerable<NhanVien>>(result);
        return View(nv);
    }

    //create

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(NhanVien nhanvien)
    {
        if (ModelState.IsValid)
        {
            var url =
                $"https://localhost:7195/api/NhanVien/create?name={nhanvien.Name}&age={nhanvien.Age}&role={nhanvien.Role}&email={nhanvien.Email}&luong={nhanvien.Luong}&status={nhanvien.Status}";
            var response = await _client.PostAsync(url, null);
            if (response.IsSuccessStatusCode) return RedirectToAction("Show");
        }
        return View();
    }

    //edit
    [HttpGet]
    public IActionResult Edit(Guid id)
    {
        var url = $"https://localhost:7195/api/NhanVien/{id}";
        var response = _client.GetAsync(url).Result;
        var result = response.Content.ReadAsStringAsync().Result;
        var nv = JsonConvert.DeserializeObject<NhanVien>(result);
        return View(nv);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(NhanVien nhanvien)
    {
        if (ModelState.IsValid)
        {
            var url =
                $"https://localhost:7195/api/NhanVien/edit/{nhanvien.Id}?name={nhanvien.Name}&age={nhanvien.Age}&role={nhanvien.Role}&email={nhanvien.Email}&luong={nhanvien.Luong}&status={nhanvien.Status}";
            var response = await _client.PutAsync(url, null);
            if (response.IsSuccessStatusCode) return RedirectToAction("Show");
        }

        return View();
    }

    //delete
    public async Task<IActionResult> Delete(Guid id)
    {
        var url = $"https://localhost:7195/api/NhanVien/delete/{id}";
        var response = await _client.DeleteAsync(url);
        if (response.IsSuccessStatusCode) return RedirectToAction("Show");
        return BadRequest();
    }

    //detail
    public IActionResult Detail(Guid id)
    {
        var url = $"https://localhost:7195/api/NhanVien/{id}";
        var response = _client.GetAsync(url).Result;
        var result = response.Content.ReadAsStringAsync().Result;
        var nv = JsonConvert.DeserializeObject<NhanVien>(result);
        return View(nv);
    }
}

AppView/Views/Bmi/Calculate.cshtml
@{
    ViewBag.Title = "title";
    var result = Convert.ToDouble(ViewBag.Bmi);
    Layout = "_Layout";
}
<form asp-action="Calculate">
    <label>Enter Weight</label>
    <input name="weight" class="form-control-sm" placeholder="Enter KG"/>
    <br/>
    <label class="mt-4">Enter Height</label>
    <input name="height" class="form-control-sm" placeholder="Enter Meter"/>
    <br/>
    <input type="submit" value="Calculate" class="btn btn-primary mt-4"/>
    <hr/>
</form>
<div>
    <h1>RESULT</h1>
    @if (result > 0)
    {
        <p>Your BMI is: @result</p>
    }
</div>

AppView/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AppView/Views/NhanVien/Create.cshtml
@model AppData.Model.NhanVien

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>NhanVien</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control"/>
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <input asp-for="Role" class="form-control"/>
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Luong" class="control-label"></label>
                <input asp-for="Luong" class="form-control"/>
                <span asp-validation-for="Luong" class="text-danger"></span>
            </div>
            <div class="form-group">
               <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status"  class="form-select" aria-label="Default select example">
                    <option value="True">Active</option>
                    <option value="False">Deactive</option>
                </select>
            </div>
            <div class="form-group mt-4">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Show">Back to List</a>
</div>

AppView/Views/NhanVien/Detail.cshtml
@model AppData.Model.NhanVien

@{
    ViewData["Title"] = "Detail";
}

<h1>Detail</h1>

<div>
    <h4>NhanVien</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Role)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Luong)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Luong)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Show">Back to List</a>
</div>

AppView/Views/NhanVien/Edit.cshtml
@model AppData.Model.NhanVien

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>NhanVien</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control"/>
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <input asp-for="Role" class="form-control"/>
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Luong" class="control-label"></label>
                <input asp-for="Luong" class="form-control"/>
                <span asp-validation-for="Luong" class="text-danger"></span>
            </div>
            <div class="form-group">
               <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status"  class="form-select" aria-label="Default select example">
                    <option value="True">Active</option>
                    <option value="False">Deactive</option>
                </select>
            </div>
            <div class="form-group mt-4">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Show">Back to List</a>
</div>

AppView/Views/NhanVien/Show.cshtml
@model IEnumerable<AppData.Model.NhanVien>

@{
    ViewData["Title"] = "Show";
}

<h1>Show</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Role)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Luong)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Role)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Luong)
            </td>
            <td>
                @if(item.Status == true){
                    <span class="text-success">Đang làm việc</span>
                }else{
                    <span class="text-danger">Đã nghỉ việc</span>
                }
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Detail", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
    </tbody>
</table>

AppView/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - AppView</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/AppView.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="NhanVien" asp-action="Show">AppView</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="NhanVien" asp-action="Show">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Bmi" asp-action="Calculate">BMI</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>